In [20]:
import pandas as pd
import os
import csv
from io import StringIO
import matplotlib.pyplot as plt
from os import path

In [33]:
dfs=[]
counter=0
for file in os.listdir('Data_new_2'):
    if file.endswith(".csv"): 
        open_file=open('Data_new_2/' + file,'r') 
        content = open_file.read()
        f = StringIO(content)
        reader = csv.reader(f, delimiter=',')
        arr = []
        for row in reader:
            arr.append(row)
        df=pd.DataFrame(arr)
        counter+=1
        print(f"data frame number: {counter}")
        print(file)
        print(df)
        dfs.append(df)
        continue
    else:
        continue

data frame number: 1
Hydroelectric_Power_Consumption-Production,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017      2770.011
2   2016      2472.442
3   2015      2321.177
4   2014      2466.577
5   2013      2562.382
6   2012      2628.702
7   2011      3102.852
8   2010      2538.541
9   2009      2668.824
10  2008      2511.108
11  2007      2446.389
12  2006      2869.035
13  2005      2702.942
14  2004      2688.468
15  2003      2792.539
16  2002      2689.017
17  2001      2241.858
18  2000      2811.116
19  1999      3267.575
20  1998      3297.054
21  1997      3640.458
22  1996      3589.656
23  1995      3205.307
24  1994      2683.457
25  1993      2891.613
26  1992      2617.436
27  1991      3015.943
28  1990      3046.391
29  1989      2837.263
..   ...           ...
40  1978      2936.983
41  1977      2333.252
42  1976      2976.265
43  1975      3154.607
44  1974       3176.58
45  1973      2861.448
46  1972      2863.865
47  1971      2824.151
48  1970      2633.547
49  1969      2647.983
50  1968      2348.629
51  1967      2346.664
52  1966      2061.519
53  1965      2059.077
54  1964      1886.314
55  1963      1771.355
56  1962      1816.141
57  1961      1656.463
58  1960      1607.975
59  1959      1548.465
60  1958      1591.967
61  1957      1515.613
62  1956      1434.711
63  1955      1359.844
64  1954      1359.772
65  1953      1412.859
66  1952      1465.812
67  1951      1423.795
68  1950      1415.411
69  1949      1424.722

[70 rows x 2 columns]
data frame number: 2
Comm._and_Indus._Sectors_Large-Scale_Solar_Net_Summer_Capacity,_Annual.csv
       0          1
0   Year  megawatts
1   2019      359.9
2   2018      360.6
3   2017      352.1
4   2016      320.2
5   2015      294.3
6   2014      231.1
7   2013      200.6
8   2012      107.2
9   2011       58.5
10  2010        8.6
11  2009        1.1
12  2008        1.1
13  2007        1.0
14  2006        0.0
15  2005        0.0
16  2004        0.0
17  2003        0.0
18  2002        0.0
19  2001        0.0
data frame number: 3
Residential_Sector_Total_Consumption_of_Renewable_Energy,_Annual.csv
       0                1
0   Year  Quadrillion Btu
1   2019        0.7349188
2   2018       0.68028116
3   2017       0.56491245
4   2016      0.548840232
5   2015      0.602329627
6   2014      0.735485526
7   2013      0.711025714
8   2012      0.538440791
9   2011      0.560394532
10  2010      0.541513849
11  2009       0.59262216
12  2008      0.554835749
13  2007    0.49704447213
14  2006    0.45080116249
15  2005    0.49606775881
16  2004    0.47513057416
17  2003    0.46482080837
18  2002    0.44349710501
19  2001    0.43462283396
20  2000    0.48630650957
21  1999    0.45885827833
22  1998    0.44947211521
23  1997    0.49995760737
24  1996    0.61030203274
25  1995    0.58932423448
26  1994    0.58796907805
27  1993    0.61692235441
28  1992    0.70487348327
29  1991    0.67234818222
30  1990    0.64022545234
data frame number: 4
Electric_Power_Sector_Geothermal_Net_Summer_Capacity,_Annual.csv
       0          1
0   Year  megawatts
1   2019     2544.5
2   2018     2501.6
3   2017     2485.6
4   2016     2516.6
5   2015     2541.5
6   2014     2514.3
7   2013     2607.0
8   2012     2592.1
9   2011     2409.2
10  2010     2404.6
11  2009     2381.9
12  2008     2228.8
13  2007     2214.2
14  2006    2294.78
15  2005     2297.1
16  2004    2163.88
17  2003    2135.25
18  2002    2254.25
19  2001    2217.01
data frame number: 5
Electric_Power_Sector_Large-Scale_Solar_Net_Summer_Capacity,_Annual.csv
       0          1
0   Year  megawatts
1   2019    43540.4
2   2018    32095.8
3   2017    26572.7
4   2016    21630.6
5   2015    13374.2
6   2014    10092.2
7   2013     6421.9
8   2012     3062.9
9   2011     1465.0
10  2010      857.8
data frame number: 6
Comm._and_Indus._Sectors_Wind_Net_Summer_Capacity,_Annual.csv
       0          1
0   Year  megawatts
1   2019      103.5
2   2018      103.5
3   2017       97.1
4   2016       88.6
5   2015       87.1
6   2014       75.9
7   2013       50.9
8   2012       38.5
9   2011       28.9
10  2010       13.1
11  2009        1.2
12  2008        0.0
13  2007        0.0
14  2006        0.0
15  2005        0.0
16  2004        0.0
17  2003        0.0
18  2002        0.0
19  2001        0.0
data frame number: 7
Crude_Oil_Production,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017     19537.928
2   2016     18548.383
3   2015     19632.281
4   2014      18530.51
5   2013     15805.982
6   2012      13791.02
7   2011     11945.911
8   2010     11590.974
9   2009     11322.969
10  2008     10608.979
11  2007     10741.447
12  2006     10766.775
13  2005     10974.152
14  2004     11550.086
15  2003     11959.568
16  2002     12160.213
17  2001     12281.566
18  2000     12358.101
19  1999     12451.046
20  1998      13235.13
21  1997      13658.02
22  1996     13722.899
23  1995     13886.754
24  1994     14102.563
25  1993      14494.39
26  1992     15222.863
27  1991     15700.826
28  1990     15571.185
29  1989     16116.883
..   ...           ...
40  1978     18433.653
41  1977     17453.737
42  1976     17261.844
43  1975     17729.318
44  1974     18574.993
45  1973     19493.237
46  1972     20041.134
47  1971     20032.701
48  1970      20401.21
49  1969     19556.156
50  1968     19308.444
51  1967     18651.304
52  1966     17561.025
53  1965     16521.381
54  1964     16163.568
55  1963     15965.793
56  1962     15521.896
57  1961     15206.196
58  1960     14934.611
59  1959     14932.622
60  1958     14204.125
61  1957     15178.026
62  1956     15180.241
63  1955     14409.682
64  1954      13426.93
65  1953     13671.076
66  1952     13281.049
67  1951     13036.724
68  1950     11446.729
69  1949     10683.252

[70 rows x 2 columns]
data frame number: 8
Coal_Production,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017     15619.866
2   2016     14667.089
3   2015     17946.095
4   2014     20285.705
5   2013     20001.304
6   2012     20676.893
7   2011     22221.407
8   2010     22038.226
9   2009     21623.721
10  2008     23851.368
11  2007     23492.742
12  2006      23789.51
13  2005     23185.189
14  2004     22852.099
15  2003     22093.652
16  2002     22732.237
17  2001      23547.08
18  2000     22735.478
19  1999     23295.084
20  1998     24045.198
21  1997     23309.614
22  1996     22790.148
23  1995      22129.55
24  1994     22202.083
25  1993     20335.654
26  1992     21694.132
27  1991     21636.424
28  1990     22487.548
29  1989     21360.178
..   ...           ...
40  1978     14909.809
41  1977     15754.741
42  1976     15653.687
43  1975     14989.315
44  1974     14074.451
45  1973     13992.126
46  1972     14091.685
47  1971     13185.523
48  1970     14607.064
49  1969     13863.346
50  1968     13608.678
51  1967     13825.487
52  1966     13467.679
53  1965     13055.285
54  1964     12523.881
55  1963     11849.229
56  1962      10900.56
57  1961     10447.091
58  1960     10817.398
59  1959     10777.984
60  1958     10783.088
61  1957     13061.393
62  1956     13306.334
63  1955     12369.608
64  1954     10542.448
65  1953     12277.746
66  1952     12734.313
67  1951     14419.325
68  1950     14060.135
69  1949     11973.882

[70 rows x 2 columns]
data frame number: 9
Commercial_Sector_Total_Consumption_of_Renewable_Energy,_Annual.csv
       0                1
0   Year  Quadrillion Btu
1   2019         0.438118
2   2018     0.3553881606
3   2017     0.2539445776
4   2016    0.24158824225
5   2015     0.2287296272
6   2014    0.19939596551
7   2013     0.1812145771
8   2012    0.16001230176
9   2011    0.15392123957
10  2010    0.14162837466
11  2009    0.13664494189
12  2008     0.1302567032
13  2007    0.12139310911
14  2006    0.12008505874
15  2005     0.1213052072
16  2004    0.11952206176
17  2003     0.1139647451
18  2002     0.1046847559
19  2001    0.10131008106
20  2000     0.1282840772
21  1999     0.1291199405
22  1998    0.12721697332
23  1997    0.13859019528
24  1996    0.13578279726
25  1995    0.11873397295
26  1994    0.11183963272
data frame number: 10
Geothermal_Energy_Consumption-Production,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017       210.991
2   2016       209.604
3   2015       211.836
4   2014        214.49
5   2013       214.006
6   2012       211.592
7   2011       212.311
8   2010       207.979
9   2009       200.185
10  2008       192.433
11  2007       185.774
12  2006         181.2
13  2005       180.703
14  2004       178.147
15  2003       173.445
16  2002       171.164
17  2001       164.461
18  2000       164.364
19  1999       170.921
20  1998        168.45
21  1997       166.698
22  1996       163.359
23  1995       152.057
24  1994       173.464
25  1993       185.673
26  1992       178.699
27  1991       177.626
28  1990       170.747
29  1989       161.539
..   ...           ...
40  1978        30.851
41  1977        37.382
42  1976        37.513
43  1975         33.78
44  1974         25.61
45  1973        20.422
46  1972        15.079
47  1971         5.739
48  1970         5.511
49  1969         6.422
50  1968         4.532
51  1967           3.3
52  1966         1.958
53  1965         1.978
54  1964         2.132
55  1963          1.76
56  1962         1.061
57  1961         1.001
58  1960         0.359
59  1959            NA
60  1958            NA
61  1957            NA
62  1956            NA
63  1955            NA
64  1954            NA
65  1953            NA
66  1952            NA
67  1951            NA
68  1950            NA
69  1949            NA

[70 rows x 2 columns]
data frame number: 11
Total_Biomass_Energy_Production,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017      5037.642
2   2016      4981.956
3   2015      4914.367
4   2014      5028.791
5   2013      4823.977
6   2012       4528.61
7   2011      4630.057
8   2010      4452.006
9   2009      3952.617
10  2008       3868.25
11  2007       3472.08
12  2006      3211.515
13  2005      3101.186
14  2004      2996.017
15  2003      2804.778
16  2002      2705.406
17  2001      2624.162
18  2000      3005.661
19  1999      2965.132
20  1998       2928.93
21  1997      3107.908
22  1996      3155.301
23  1995      3099.082
24  1994      3027.534
25  1993      2908.446
26  1992      2931.678
27  1991      2781.797
28  1990      2735.112
29  1989      3159.357
..   ...           ...
40  1978      2037.605
41  1977      1838.332
42  1976      1713.373
43  1975      1498.734
44  1974      1539.662
45  1973      1529.068
46  1972      1503.065
47  1971      1432.323
48  1970      1430.962
49  1969      1440.487
50  1968      1419.495
51  1967      1340.249
52  1966      1368.985
53  1965      1334.761
54  1964      1336.802
55  1963      1323.316
56  1962      1300.242
57  1961      1294.762
58  1960       1319.87
59  1959      1352.874
60  1958      1323.123
61  1957      1333.581
62  1956      1415.871
63  1955      1424.143
64  1954      1394.327
65  1953      1418.601
66  1952      1474.369
67  1951      1534.669
68  1950      1562.307
69  1949      1549.262

[70 rows x 2 columns]
data frame number: 12
Natural_Gas_(Dry)_Production,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017     27847.897
2   2016     27649.297
3   2015     28066.882
4   2014     26718.073
5   2013     24859.072
6   2012     24610.065
7   2011      23405.72
8   2010     21805.763
9   2009      21139.45
10  2008     20702.884
11  2007     19786.209
12  2006     19021.706
13  2005     18556.015
14  2004     19074.254
15  2003     19633.304
16  2002     19382.055
17  2001     20165.567
18  2000     19661.529
19  1999     19340.703
20  1998     19613.295
21  1997     19393.851
22  1996     19344.268
23  1995     19082.245
24  1994     19348.013
25  1993     18584.037
26  1992       18375.1
27  1991     18228.736
28  1990     18326.155
29  1989     17847.275
..   ...           ...
40  1978     19485.219
41  1977     19565.321
42  1976     19480.319
43  1975     19640.343
44  1974     21210.145
45  1973     22187.349
46  1972     22207.545
47  1971     22279.791
48  1970      21665.67
49  1969     20446.462
50  1968     19067.853
51  1967     17943.168
52  1966     17010.742
53  1965     15775.441
54  1964     15298.396
55  1963     14512.781
56  1962     13716.861
57  1961     13104.734
58  1960     12656.133
59  1959     11951.826
60  1958     10942.235
61  1957     10605.254
62  1956     10002.147
63  1955      9344.668
64  1954      8681.785
65  1953      8338.838
66  1952      7963.599
67  1951      7415.733
68  1950      6232.975
69  1949      5377.243

[70 rows x 2 columns]
data frame number: 13
Electric_Power_Sector_Wind_Net_Summer_Capacity,_Annual.csv
       0          1
0   Year  megawatts
1   2019   104344.3
2   2018    94028.1
3   2017    87492.3
4   2016    81198.0
5   2015    72486.3
6   2014    64155.6
7   2013    59922.5
8   2012    59036.3
9   2011    45647.0
10  2010    39121.4
11  2009    34294.6
12  2008    24651.3
13  2007    16515.1
14  2006   11350.75
15  2005    8719.17
16  2004     6463.7
17  2003    6001.79
18  2002    4416.64
19  2001    3893.64
data frame number: 14
Total_Primary_Energy_Consumption,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017     97735.387
2   2016     97581.919
3   2015     97526.034
4   2014     98490.661
5   2013     97340.441
6   2012     94534.976
7   2011     96976.026
8   2010     97580.057
9   2009     94117.614
10  2008     98890.755
11  2007    101014.753
12  2006      99484.49
13  2005    100187.721
14  2004    100089.702
15  2003     97917.504
16  2002     97643.478
17  2001     96169.669
18  2000     98816.545
19  1999     96648.392
20  1998     95017.738
21  1997     94600.341
22  1996     94020.528
23  1995     91030.608
24  1994     89087.341
25  1993     87365.525
26  1992     85782.166
27  1991     84437.217
28  1990     84484.553
29  1989     84785.325
..   ...           ...
40  1978     79950.406
41  1977      77961.33
42  1976     75974.826
43  1975     71964.553
44  1974     73962.369
45  1973      75683.69
46  1972     72687.867
47  1971     69282.843
48  1970     67838.325
49  1969      65614.02
50  1968     62414.507
51  1967     58904.521
52  1966     57014.332
53  1965     54015.001
54  1964     51814.788
55  1963     49644.195
56  1962     47826.437
57  1961     45737.837
58  1960     45086.455
59  1959     43465.722
60  1958     41645.028
61  1957     41787.186
62  1956     41754.252
63  1955     40207.971
64  1954     36639.382
65  1953     37664.468
66  1952     36747.825
67  1951      36974.03
68  1950     34615.768
69  1949     31981.503

[70 rows x 2 columns]
data frame number: 15
Total_Consumption_of_Renewable_Energy_by_All_Sectors,_Annual.csv
       0                1
0   Year  Quadrillion Btu
1   2019       11.6635636
2   2018     11.383109868
3   2017     11.016044718
4   2016     10.256479683
5   2015      9.613234493
6   2014      9.721107937
7   2013     9.4406907029
8   2012     8.8202414495
9   2011     9.1193277375
10  2010     8.1639624209
11  2009     7.6027617226
12  2008     7.1730500097
13  2007     6.5296928291
14  2006     6.6408129213
15  2005     6.2358780288
16  2004      6.076220079
17  2003     5.9474527138
18  2002     5.8678743239
19  2001     5.3065089663
data frame number: 16
Total_Fossil_Fuels_Production,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017     68051.504
2   2016      65634.87
3   2015     70212.746
4   2014     69630.697
5   2013     64198.584
6   2012     62323.827
7   2011     60543.191
8   2010     58216.251
9   2009     56659.922
10  2008     57582.589
11  2007     56428.986
12  2006     55933.826
13  2005     55049.197
14  2004     55942.289
15  2003     56032.784
16  2002     56833.673
17  2001     58541.348
18  2000     57366.024
19  1999     57614.481
20  1998     59314.083
21  1997     58856.691
22  1996     58387.225
23  1995     57540.133
24  1994     58043.638
25  1993     55822.082
26  1992     57655.057
27  1991     57871.727
28  1990     58559.602
29  1989     57482.679
..   ...           ...
40  1978     55074.118
41  1977     55100.782
42  1976     54722.896
43  1975     54733.273
44  1974     56330.758
45  1973     58241.491
46  1972     58937.904
47  1971      58041.56
48  1970     59186.071
49  1969     56285.569
50  1968     54306.187
51  1967     52597.132
52  1966     50035.367
53  1965     47234.902
54  1964     45788.951
55  1963     44037.181
56  1962     41731.885
57  1961     40307.136
58  1960     39869.117
59  1959     39045.216
60  1958     37216.322
61  1957     40133.484
62  1956     39771.452
63  1955      37363.68
64  1954      33764.33
65  1953     35349.336
66  1952     34976.732
67  1951     35792.151
68  1950     32562.667
69  1949     28748.176

[70 rows x 2 columns]
data frame number: 17
Electric_Power_Sector_Conventional_Hydroelectric_Net_Summer_Capacity,_Annual.csv
       0          1
0   Year  megawatts
1   2019    79785.9
2   2018    79720.2
3   2017    79585.1
4   2016    79556.2
5   2015    79385.5
6   2014    79376.6
7   2013    78521.7
8   2012    78073.7
9   2011    77721.4
10  2010    78101.3
11  2009    78159.3
12  2008    77574.5
13  2007    77523.3
14  2006   77363.87
15  2005   77112.83
16  2004   77196.86
17  2003    77901.2
18  2002   78297.34
19  2001   77844.57
data frame number: 18
Natural_Gas_Plant_Liquids_Production,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017      5045.812
2   2016      4770.102
3   2015      4567.489
4   2014      4096.409
5   2013      3532.226
6   2012       3245.85
7   2011      2970.152
8   2010      2781.288
9   2009      2573.782
10  2008      2419.358
11  2007      2408.589
12  2006      2355.836
13  2005      2333.842
14  2004       2465.85
15  2003       2346.26
16  2002      2559.168
17  2001      2547.136
18  2000      2610.916
19  1999      2527.649
20  1998      2420.459
21  1997      2495.207
22  1996       2529.91
23  1995      2441.583
24  1994      2390.979
25  1993      2408.002
26  1992      2362.961
27  1991       2305.74
28  1990      2174.714
29  1989      2158.342
..   ...           ...
40  1978      2245.438
41  1977      2326.983
42  1976      2327.046
43  1975      2374.297
44  1974      2471.169
45  1973      2568.779
46  1972      2597.539
47  1971      2543.544
48  1970      2512.128
49  1969      2419.605
50  1968      2321.212
51  1967      2177.174
52  1966      1995.921
53  1965      1882.795
54  1964      1803.106
55  1963      1709.378
56  1962      1592.568
57  1961      1549.114
58  1960      1460.974
59  1959      1382.783
60  1958      1286.874
61  1957      1288.811
62  1956       1282.73
63  1955      1239.721
64  1954      1113.167
65  1953      1061.677
66  1952       997.771
67  1951       920.369
68  1950       822.828
69  1949       713.799

[70 rows x 2 columns]
data frame number: 19
Solar-PV_Energy_Consumption-Production,_Annual.csv
       0             1
0   Year  Trillion Btu
1   2017       774.277
2   2016       568.665
3   2015       425.727
4   2014       336.939
5   2013       224.523
6   2012       156.849
7   2011       111.129
8   2010        90.483
9   2009        77.654
10  2008        73.814
11  2007        65.375
12  2006        60.581
13  2005        57.773
14  2004        58.295
15  2003        58.366
16  2002        59.923
17  2001        61.626
18  2000         63.43
19  1999        66.031
20  1998        67.419
21  1997         68.14
22  1996         69.11
23  1995        68.212
24  1994        67.108
25  1993        65.173
26  1992        62.865
27  1991        61.609
28  1990        58.755
29  1989        54.455
..   ...           ...
40  1978            NA
41  1977            NA
42  1976            NA
43  1975            NA
44  1974            NA
45  1973            NA
46  1972            NA
47  1971            NA
48  1970            NA
49  1969            NA
50  1968            NA
51  1967            NA
52  1966            NA